[package]
name = "nexo"
version = "6.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec", "rt"] }
futures-util = { version = "0.3", features = ["sink"] }
bytes = { version = "1", features = ["serde"] }
dashmap = "6.2.1"
dotenv = "0.15"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
hashlink = "0.12.2"
priority-queue = "2"
rusqlite = { version = "0.40.2", features = ["bundled", "uuid", "time"] }
bytemuck = { version = "1.14", features = ["derive"] }
parking_lot = "0.12"

[lints.rust]
unsafe_code = "deny"
unused = "deny"
deprecated = "deny"

[lints.clippy]
unwrap_used = "deny"
todo = "deny"
unimplemented = "deny"
dbg_macro = "deny"
allow_attributes = "deny"
too_many_arguments = "allow"

[profile.release]
lto = "fat"
codegen-units = 1
incremental = false


[dev-dependencies]
tempfile = "3.24.0"
base64 = "0.23"
